services:
    App\Infrastructure\Messenger\SagaMessageHandler:
        tags:
          - { name: messenger.message_handler }
        bind:
            $messageBus: '@processmanager.message.bus'
            $logger: '@monolog.logger.process_manager'
