services:
  App\UI\Command\:
    resource: '%kernel.project_dir%/src/UI/Command'
    autowire: true
    autoconfigure: true
#    bind:
#      $messageBus: '@processmanager.message.bus'
#      $sagaStateRepository: '@App\Infrastructure\SagaState\RedisStateRepository'
