# Core
services:

    app.messagebus.serializer:
        class: 'App\Infrastructure\Messenger\AMQPMessageSerializer'
        arguments:
            $targetBusName: 'processmanager.message.bus'
            $logger: '@monolog.logger.process_manager'

    App\Infrastructure\Messenger\AddAmqpStampMiddleware:

framework:
    messenger:

        failure_transport: failure_transport

        transports:

            failure_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'app.messagebus.serializer'
                options:
                    prefetch_count: 1
                    exchange:
                        name: failure_messages
                        type: topic
                    queues:
                        failure_messages:
                            binding_keys: [ '#' ]

            processmanager_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'app.messagebus.serializer'
                options:
                    prefetch_count: 1
                    exchange:
                        name: external_messages
                        type: topic
                    queues:
                        messages_for_processmanager:
                            binding_keys:
                                - 'ProcessManager.Command.*'
                                - '*.Event.*'
#                            arguments:
#                                x-max-priority: 2
#                                x-ha-policy: 'all'
                retry_strategy:
                    max_retries: 0
                    delay: 1000

            debug_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'app.messagebus.serializer'
                options:
                    prefetch_count: 1
                    exchange:
                        name: external_messages
                        type: topic
                    queues:
                        debug_messages:
                            binding_keys: [ '#' ]
                retry_strategy:
                    max_retries: 2
                    delay: 1000

        routing:
            'App\Infrastructure\Messenger\SagaMessage': processmanager_transport

        buses:
            processmanager.message.bus:
                middleware:
                    - 'App\Infrastructure\Messenger\AddAmqpStampMiddleware'
